### ISSUE TITLE
Изменение размеров автомобиля ВАЗ 2107

### ISSUE THREAD

**Issue by Kes001** [Der-Meister92/MyFirstCartoon-#1]
Функция, рисующая автомобиль ВАЗ 2107, не дает возможности изменить размер машины.   
SemerkaDraw (int x, int y)  
Добавление параметров, которые могли бы менять высоту и длину автомобиля, позволили бы использовать функцию более гибко.

**Comment by Eisenmann-92** [comment]
Для функции **SemerkaDraw** добавлен параметр изменения размера **_Size_**. 
Отдельные параметры изменения высоты и длины автомобиля считаю в данной функции неприемлемыми, так как рисуется конкретная марка автомобиля и пропорции должны быть соблюдены. В противном случае это будет считаться  изменением конструкции транспортного средства)))
